language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - REACT_APP_API_BASE_URL=http://localhost:8080
    - PACT_BROKER_BASE_URL=https://andyballingall.pact.dius.com.au
    # PACT_BROKER_TOKEN is encrypted below
    - secure: "g0umfnTc26SLWf3IZSOIWvy1rQVqA9oheC7Y+JxdgGhCJMvpYAmy4ukCz4FaDIcWJJMyKayOg3VXWdirrlX3ulYuDZzw1+foycaP+cVcjgbG85rzs6nn8RCt2VJsYInusGEnuqRdONWsbQVcGaE1q6k3F3kkwCRw5QPNlCAnHNAvsvvPEbiVgVB4r/dbjqFH6A4t8xTTlyK0t4CSIdk46vTfyiX6AmAUZ6q8VoBJ66H1R5ey0QCy2bEuEvMOqqCBWZ24LKcYSP1Ilf+8vj4a85JJ2LFRIZFcsSg/mm6HaMFaqWcPQ6Fwipu0zzK6gW2FMl5GDVN838Mthv17F378fNEp9rkC+Rfuft39V2GHN9cBTjGMH+e4uurYxHxhRJS1gaONkDF9TeJdDRa4TRIOeUOLPNQTn49D6+RLWk71hwL+7z3Rh4c7x5xpQM/u1NUKNf8cIKDnxRzvWM2Ahd4CAwjt9VG1EzsvkP+fxehb+yHpyEfsvyGOXbiGYOQ9ekOaP5TOP0grbmD5Lv4joQxk/EOU8WgAf2Yb18o0iaBq/dKnjK7oAyUnxpHayal3DKVXIRXQzf+HVQRNG4jvJYTMR24/FRirgKFmdU9MaKZ3UXNFnhxj2CDERuRnS/hF1b1+6zN0bKsl8BkeTjMtYVhZPO00FSH7EZva6hjRxND1jBs="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  - make ci
